org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=epicvanguard
mod_name=Epic Vanguard
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.example.epicvanguard
mod_authors=Rafael Santos
mod_description=Companheiros Guerreiros mercenarios com IA tatica avancada, progressao e combate integrado ao Epic Fight.

